#!/usr/bin/env node
/**
 * Writes the final style tags (final.js) to api/data/style-tags.json, the file
 * the API reads. Stored beside analysis_json, not over it.
 *
 *   node tools/style-tags/export.js
 *
 * Every position takes its variation's tags (variation-map.json, through
 * shared-briefs.json). Hubs and variations not yet classified are left out, so
 * their pages show no tags rather than a guess. An axis still unresolved
 * exports as its hidden middle value: a missing word beats a wrong one.
 *
 * Labels and glossary lines come from docs/style-taxonomy.md, so the API needs
 * nothing from tools/.
 */
const fs = require('fs');
const path = require('path');
const { AXES, plans, glossaries } = require('./taxonomy');
const { MIDDLE, LABELS, finalAnswers } = require('./final');

const REPO = path.join(__dirname, '../..');
const OUT = path.join(REPO, 'api/data/style-tags.json');

function build({ final, map, shared, planList, glossary }) {
  const labels = {};
  for (const [axis, values] of Object.entries(LABELS)) {
    labels[axis] = {};
    for (const [value, label] of Object.entries(values)) {
      if (!glossary[label]) throw new Error(`docs/style-taxonomy.md: no glossary for ${label}`);
      labels[axis][value] = { label, glossary: glossary[label] };
    }
  }
  const planLabels = Object.fromEntries(
    planList.map((p) => [p.key, { label: p.label, glossary: p.glossary }])
  );

  const variations = {};
  for (const [slug, answers] of Object.entries(final)) {
    const v = {};
    for (const axis of AXES) v[axis] = answers[axis] || MIDDLE[axis];
    v.plans = answers.plans.filter((p) => planLabels[p]);
    variations[slug] = v;
  }

  const positions = {};
  for (const [fen, slug] of Object.entries(map)) {
    const owner = shared[slug] || slug;
    if (variations[owner]) positions[fen] = owner;
  }
  return { labels, plans: planLabels, variations, positions };
}

function main() {
  const read = (p) => JSON.parse(fs.readFileSync(path.join(REPO, p), 'utf8'));
  const { final } = finalAnswers();
  const out = build({
    final,
    map: read('tools/data/style-briefs/_inputs/variation-map.json'),
    shared: read('tools/style-tags/shared-briefs.json').shared,
    planList: plans(),
    glossary: glossaries(),
  });
  const body = {
    _comment:
      'Generated by tools/style-tags/export.js from the classified style briefs. Do not hand-edit; see docs/style-taxonomy.md.',
    ...out,
  };
  fs.writeFileSync(OUT, JSON.stringify(body) + '\n');
  const n = Object.keys(out.positions).length;
  console.log(
    `${Object.keys(out.variations).length} variations, ${n} positions → ${path.relative(REPO, OUT)} (${(fs.statSync(OUT).size / 1024).toFixed(0)} KB)`
  );
}

if (require.main === module) main();
module.exports = { build };
