#!/usr/bin/env node
/**
 * Writes tools/data/style-briefs/_classify/pilot-tags.md: what each classified
 * page would show, most-played first, for the owner to review.
 *
 *   node tools/style-tags/report.js
 */
const fs = require('fs');
const path = require('path');
const { finalAnswers, display } = require('./final');

const REPO = path.join(__dirname, '../..');
const BRIEFS = path.join(REPO, 'tools/data/style-briefs');

const pop = JSON.parse(fs.readFileSync(path.join(REPO, 'api/data/popularity_stats.json'), 'utf8'));
const stats = pop.positions || pop;
const map = JSON.parse(fs.readFileSync(path.join(BRIEFS, '_inputs/variation-map.json'), 'utf8'));
const games = {};
for (const [fen, slug] of Object.entries(map))
  games[slug] = (games[slug] || 0) + ((stats[fen] || {}).games_analyzed || 0);

const { final } = finalAnswers();
const rows = Object.keys(final)
  .sort((a, b) => (games[b] || 0) - (games[a] || 0))
  .map((slug) => {
    const name = JSON.parse(fs.readFileSync(path.join(BRIEFS, `${slug}.json`), 'utf8')).root.name;
    const { words, plans } = display(final[slug]);
    return `| ${name} | ${words.join(' · ') || '—'} | ${plans.join(', ') || '—'} |`;
  });

const md = `# Style tags — pilot results

What each page would show, most-played first. Generated by
\`node tools/style-tags/report.js\`; do not edit by hand. Hidden middle values
(Balanced, Sound, Flexible, standard, Intermediate) are not listed. Plans are the
first two of those both classifiers chose, or classifier A's first where they
share none.

| Opening | Tags | Plans |
| --- | --- | --- |
${rows.join('\n')}
`;
fs.writeFileSync(path.join(BRIEFS, '_classify/pilot-tags.md'), md);
console.log(`${rows.length} rows written`);
